export const Films = [
  {
    id: 1,
    name: "Omohide Poro Poro",
    year: "	20/7/1991",
    director: "Isao Takahata",
    img: "./assets/img/1.jpg",
    lore: "Bối cảnh trong phim diễn ra vào năm 1982. Nhân vật nữ chính, Taeko, 27 tuổi, là một cô gái sinh ra và lớn lên ở Tokyo. Cô là một viên chức bình thường, sống độc thân và không mấy hứng thú với công việc. Cuộc sống của Taeko trôi qua tẻ nhạt và bình lặng cho đến khi cô xin nghỉ phép một thời gian để về nông thôn giúp anh rể thu hoạch hoa rum (safflower- một loại hoa màu nghệ dùng để nhuộm vải). Trong suốt chuyến đi, những ký ức tuổi thơ về năm cuối tiểu học tràn ngập trong cô. Những mảnh ký ức cùng những việc xảy ra ở vùng quê này đã làm thay đổi hoàn toàn cuộc sống tẻ nhạt của Taeko.",
    info: 'Only Yesterday (おもひ で ぽろぽろ Omohide Poro Poro?, lit. "ký ức đổ về" [1]) là một phim hoạt hình công chiếu năm 1991 bộ phim truyền hình phim đạo diễn bởi Isao Takahata, dựa trên manga cùng tên của Okamoto Hotaru và Tone Yuko.[2] Toshio Suzuki sản xuất bộ phim và Studio Ghibli thực hiện. Nó đã được phát hành vào ngày 20 tháng 7 năm 1991 [3] Bài hát chủ đề kết thúc (愛 は 花, 君 は その 種子 Ai wa Hana Kimi wa sono Tane, thắp sáng." Tình yêu là một bông hoa, bạn là hạt giống của nó ") là một bản dịch tiếng Nhật bài hát của Amanda McBroom, " The Rose. "',
  },
  {
    id: 2,
    name: "Kurenai no Buta",
    year: "18/7/1992",
    director: "Miyazaki Hayao",
    img: "./assets/img/2.jpg",
    lore: "Bộ phim kể về câu chuyện của Porco Rosso và mối tình lãng mạn với Gina, người sở hữu và điều hành các câu lạc bộ cùng khách sạn biển dành cho phi công lái thủy phi cơ tại vùng biển Adriatic. Cốt truyện xoay quanh tình bạn giữa Porco và cô gái kỹ sư máy bay tập sự tài năng tên Fio, cùng cuộc cạnh tranh với một phi công người Mỹ nóng tính tên Curtis. Porco bị một lời nguyền khiến mặt của ông bị biến thành heo nhưng nguồn gốc của lời nguyền này không được giải thích đầy đủ trên phim. Cho dù lời nguyền biến ông thành heo không bao giờ được giải thích đầy đủ trên phim nhưng nó có một gợi ý liên quan đến việc ông rời bỏ lực lượng không quân cũng như ý chí vượt qua cái chết khi nó đã gần kề vì người mình yêu.",
    info: 'Kurenai no Buta (紅の豚, くれないのぶた) còn được biết với tên Porco Rosso là bộ phim anime thứ sáu do Miyazaki Hayao đạo diễn và sản xuất bởi Studio Ghibli, bộ phim công chiếu lần đầu tiên năm 1992. Cốt truyện lấy bối cảnh chiến tranh thế giới thứ nhất, một phi công lái máy bay chiến đấu đã trở thành một người săn tiền thưởng luôn nhằm vào những tên "Cướp biển lái máy bay" tại vùng biển Adriatic. Người phi công này bị một lời nguyền khuôn mặt của ông bị biến thành mặt heo. Ồng từng có tên là Marco Pagot nhưng từ khi bị lời nguyền ông có một tên khác được mọi người biết đến là Porco Rosso theo tiếng Ý có nghĩa là Lợn Đỏ (vì ông luôn lái máy bay màu đỏ).',
  },
  {
    id: 3,
    name: "Gake no Ue no Ponyo",
    year: "19/7/2008",
    director: "Miyazaki Hayao",
    img: "./assets/img/3.jpg",
    lore: "Nàng tiên cá Ponyo trốn khỏi gia đình dưới đại dương, nàng là con gái của vua biển cả. Tình cờ khi lên tới mặt biển, Ponyo được cậu bé Sousuke nhặt được khi đang bị mắc kẹt trong một cái chai, Sousuke đem Ponyo về nuôi và cậu bé cũng biết nó là cá thần vì nó đã giúp vết thương trên tay cậu bé biến mất. Ông vua biển biết con mình đã trốn ra ngoài, lập tức tìm bắt bằng được về. Nhưng lúc liếm vào vết thương của Sousuke, Ponyo đã nuốt máu người và trở nên mạnh mẽ không ngờ, có thể biến hóa tay chân tùy ý. Lợi dụng lúc cha mình vắng mặt, Ponyo đã nhờ các em của mình giúp sức trốn thoát để tìm gặp Sousuke. Cùng lúc trở thành người thì năng lực của Ponyo cũng từ từ biến mất…",
    info: "Gake no Ue no Ponyo (崖の上のポニョ, がけのうえのポニョ), dịch nghĩa: Ponyo trên vách đá, thường gọi Ponyo; là một bộ phim anime thực hiện bởi Studio Ghibli công chiếu năm 2008, Miyazaki Hayao đã đạo diễn và viết kịch bản cho bộ phim. Đây là bộ phim thứ tám mà Miyazaki đảm nhiệm thực hiện cho Ghibli và là phim thứ mười của ông. Cốt truyện xoay quanh một cô bé cá vàng tên Polumisharudin muốn trở thành người, cô đã kết bạn với một cậu bé năm tuổi tên Sōsuke và được cậu đặt tên là Ponyo.",
  },
  {
    id: 4,
    name: "Mononoke Hime",
    year: "12/7/1997",
    director: "Miyazaki Hayao",
    img: "./assets/img/4.jpg",
    lore: "Ngôi làng bé nhỏ của bộ tộc Emishi ở phía Đông đột nhiên bị tấn công bởi Tatarigami (tạm dịch là Tà Thần). Hoàng tử Ashitaka của tộc Emishi buộc phải dùng cung tên bắn chết Tatarigami để bảo vệ dân làng. Trong lúc chiến đấu, anh đã bị nguyền khi để những con giun quỷ (thứ bao bọc lấy Tatari Gami) bám vào tay. Lời nguyền[1] đó vừa ban cho anh một sức mạnh phi thường đồng thời cũng hủy hoại linh hồn anh cho đến chết. Nhà tiên tri trong làng bảo đó là một vị thần heo rừng đến từ Tây vực xa xôi, nó đã bị một viên đá kì dị bắn bị gãy xương, lâu dần vết thương đó thiêu đốt nó từ bên trong và biến nó thành một Tatari Gami. Vì muốn tìm hiểu nguyên nhân sự xuất hiện của Tatarigami cũng như để giải lời nguyền, Ashitaka đã cắt bỏ búi tóc trên đầu, dẫn theo con linh dương thân thiết Yakul, tiến về khu vực phía Tây. Theo lệ làng, điều này đồng nghĩa với việc anh đã chết và không ai được đưa tiễn hoàng tử Ashitaka. Nhưng hôn thê của anh - Kaya, bất chấp luật lệ đã chạy ra tiễn, cô bé còn tặng anh mặt dây chuyền bằng ngọc bích có hình lưỡi dao, thay lời chúc cho Ashitaka bình an trở về.",
    info: 'Mononoke Hime (Nhật: もののけ姫 Hepburn: Mononoke-hime?, "Công chúa Mononoke") là một bộ phim anime lấy đề tài sử thi giả tưởng của đạo diễn Miyazaki Hayao do hãng phim Ghibli sản xuất năm 1997. "Mononoke" (物の怪?) không phải là một cái tên, đây là cách gọi chung trong tiếng Nhật có nghĩa là ma quỷ hay quái vật, ở đây có thể hiểu là "linh hồn oán hận". Phim được công chiếu lần đầu tại Nhật vào ngày 12 tháng 7 năm 1997, và tại Hoa Kỳ vào ngày 29 tháng 10 năm 1999.Phim lấy bối cảnh những cánh rừng bạt ngàn và bí ẩn xen lẫn nhiều yếu tố kỳ ảo vào cuối thời Muromachi (1392 - 1572), nơi mà súng đạn dần thay thế cho đao kiếm, sự thống trị của các samurai suy yếu đến mức biến họ thành những tên cướp bóc. Vào thời điểm này, người Nhật Bản nói riêng và loài người nói chung đã có ý thức chinh phục, khai phá thiên nhiên bằng sức lực, trí tuệ của mình. Tuy nhiên sự khai thác bừa bãi đã làm thiên nhiên nổi giận, không ít lần giáng tai họa xuống loài người.',
  },
  {
    id: 5,
    name: "Pom Poko",
    year: "16/07/1994",
    director: "Isao Takahata",
    img: "./assets/img/5.jpg",
    lore: "Câu chuyện bắt đầu vào cuối những năm 1960 ở Nhật Bản. Một nhóm tanuki đang bị đe dọa bởi một dự án phát triển ngoại ô khổng lồ có tên New Tama, trên đồi Tama ở ngoại ô Tokyo. Sự phát triển đang cắt vào môi trường sống rừng của chúng và phân chia đất đai của chúng. Câu chuyện tiếp tục vào đầu những năm 1990 ở Nhật Bản, trong những năm đầu của thời đại Heisei. Với không gian sống hạn chế và thực phẩm giảm hàng năm, tanuki bắt đầu chiến đấu với nhau để giành lấy nguồn tài nguyên ngày càng cạn kiệt, nhưng dưới sự thúc giục của mẫu hệ Oroku, họ quyết định thống nhất để ngăn chặn sự phát triển.Một số tanuki lãnh đạo cuộc kháng chiến, bao gồm thủ lĩnh hung hăng Gonta, guru già Seizaemon, người phụ nữ khôn ngoan Oroku, và Shoukichi trẻ trung và tháo vát. Sử dụng các kỹ năng ảo ảnh của họ (mà họ phải học lại sau khi quên chúng), họ thực hiện một số trò tiêu khiển bao gồm phá hoại công nghiệp. Những cuộc tấn công này làm bị thương và thậm chí giết người, khiến công nhân xây dựng sợ hãi bỏ việc, nhưng nhiều công nhân ngay lập tức thay thế họ. Trong tuyệt vọng, tanuki gửi sứ giả để tìm kiếm sự giúp đỡ từ các trưởng lão huyền thoại khác nhau từ các khu vực khác.",
    info: "Pom Poko (tiếng Nhật: 平成狸合戦ぽんぽこ, Hepburn: Heisei Tanuki Gassen Ponpoko, lit. 'Heisei-era Raccoon Dog War Ponpoko') là một bộ phim hoạt hình giả tưởng Nhật Bản năm 1994 do Takahata Isao viết kịch bản và đạo diễn, hoạt hình bởi Studio Ghibli cho Tokuma Shoten, Nippon Television Network và Hakuhodo, và được phân phối bởi Toho.Một câu chuyện ngụ ngôn về môi trường, câu chuyện có tanuki, hoặc chó gấu trúc Nhật Bản (được gọi không chính xác là 'gấu trúc' trong hộp thoại tiếng Anh). Trong văn hóa dân gian Nhật Bản, tanuki được coi là sinh vật huyền bí, có khả năng biến hình thành người hoặc các vật thể khác. Chúng là một loài rất hòa đồng, tinh nghịch, quá vui vẻ và thích những món ăn ngon để trở thành mối đe dọa thực sự - không giống như kitsune (cáo) và những người thay đổi hình dạng khác.",
  },
  {
    id: 6,
    name: "Majo no Takkyūbin",
    year: "29/7/1989",
    director: "Miyazaki Hayao",
    img: "./assets/img/6.jpg",
    lore: "Kiki là một phù thủy trẻ vừa tổ chức sinh nhật lần thứ mười ba. Đó là một ngày quan trọng trong gia đình cô: theo truyền thống ở độ tuổi này, các phù thủy phải rời xa cha mẹ và định cư một năm ở một thành phố mới để hoàn thiện việc học của mình. Kiki lắng nghe bản tin thời tiết trên đài phát thanh thông báo thời tiết , vì vậy, cô quyết định mình sẽ rời đi vào buổi tối cùng ngày. Mặc dù mẹ cô hơi lo lắng, nhưng cô không cố gắng trì hoãn việc khởi hành. Bà đưa cho con gái chiếc váy đen truyền thống của phù thủy mà Kiki thấy quá buồn tẻ so với sở thích của cô, trong khi cha cô đang gọi những người hàng xóm đến dự lễ chia tay. Chia tay bạn bè và chộp lấy chiếc radio màu đỏ của cha, Kiki cùng với chú mèo Zizi ngồi trên cây chổi của mẹ, va vào cành cây khi cất cánh, bắt đầu một hành trình dài. Cô sớm gặp một phù thủy trẻ, lớn tuổi và hơi kiêu kỳ, tiết lộ với cô rằng cô ấy chuyên về chiêm tinh học. Kiki thắc mắc về chuyên môn của mình khi cô bị bất ngờ bởi một cơn giông dữ dội buộc cô phải trú ẩn trong một chiếc xe chở gia súc. Vào buổi sáng sớm, cô trở nên ngạc nhiên khi nhìn thấy đại dương, gần đó là nơi cô mơ ước được định cư. Ngay sau khi đến nơi, Kiki vô tình gây náo loạn trên đường, suýt đâm phải ô tô. Vì vi phạm, bảo vệ địa phương cố gắng liên lạc với bố mẹ cô, nhưng một cậu bé tên Tombo đã cố tình đánh lạc hướng an để Kiki trốn thoát. Cô nhanh chóng đặt ra câu hỏi là mình nên ở đâu: ở tuổi mười ba và không có nhiều tiền, cô không thể thuê phòng khách sạn. Dựa lưng một mình vào bức tường thấp, chú mèo Jiji của cô nghĩ đến việc tìm kiếm một thành phố thân thiện hơn. Cả hai đều bị gián đoạn bởi một người phụ nữ mang thai lao ra khỏi tiệm bánh của mình vì một khách hàng đã quên núm vú giả của con cô ấy. Trở lại tiệm bánh, bà của tiệm Osono hiểu rằng cô gái trẻ không có chỗ ngủ nên đã cho cô ở nhờ qua đêm trong một căn phòng thuộc tầng một của một nhà kho.",
    info: "Dịch vụ giao hàng của phù thủy Kiki (Nhật: 魔女の宅急便 Hepburn: Majo no Takkyūbin?, dịch thô: Dịch vụ giao hàng của phù thủy) là một phim điện ảnh hoạt hình kỳ ảo của Nhật Bản, do Studio Ghibli thực hiện với kịch bản, sản xuất và đạo diễn bởi Miyazaki Hayao. Truyện phim xoay quanh một nữ phù thủy nhỏ tuổi tên là Kiki. Cô bé chuyển đến sống ở một thành phố mới và sử dụng năng lực bay trên không của mình để kiếm sống. Theo Miyazaki, bộ phim đặc biệt miêu tả hố sâu ngăn cách giữa tính tự lập và sự phụ thuộc của các cô bé tuổi mới lớn ở Nhật Bản.",
  },
  {
    id: 7,
    name: "Kaze Tachinu",
    year: "20/7/2013",
    director: "Miyazaki Hayao",
    img: "./assets/img/7.jpg",
    lore: "Nhân vật chính của Kaze Tachinu là Jirō, sinh ra vào buổi giao thời của nước Nhật cũ và nước Nhật mới với niềm yêu thích mãnh liệt với không trung và những giấc mơ được lái máy bay chinh phục bầu trời, vượt qua những không gian cũ kỹ của nước Nhật. Giấc mơ chinh phục bầu trời của cậu gặp phải một trở ngại không thể vượt qua: cậu bị cận nặng và không thể trở thành phi công. Những cảm hứng từ Caproni, một kỹ sư hàng không người Ý với vẻ ngoài bảnh bao đã đem lại cho Jirō một giấc mơ mới: tự tay thiết kế ra những chiếc máy bay cho nước Nhật. Vượt qua cơn đại địa chấn phá hủy cả thành phố Tokyo năm 1923, những khó khăn trong cuộc sống của một sinh viên kỹ thuật sau thảm họa của đất nước, Jiro đã trở thành một kỹ sư thiết kế máy bay chiến đấu và tìm thấy được một nửa trái tim của mình - Naoko, một cô gái bé nhỏ, yếu đuối, nhưng luôn xinh tươi, yêu đời.",
    info: "Kaze Tachinu (風立ちぬ Gió nổi?) là một phim hoạt hình dã sử với kịch bản và đạo diễn thực hiện bởi Miyazaki Hayao, phát hành vào mùa hè năm 2013.[5] Bộ phim dựa trên bộ truyện tranh cùng tên, vốn chính bộ truyện dựa trên một truyện ngắn được viết vào giai đoạn 1936-1937 của Hori Tatsuo (28/12/1904 – 28/05/1953), một nhà văn, nhà thơ và dịch giả sống vào giữa thế kỷ 20 (thời kỳ Showa) của Nhật Bản. Miyazaki cho biết đây sẽ là bộ phim cuối cùng của ông.[6] Tên tiếng Anh của phim là The Wind Rises.[7]",
  },
  {
    id: 8,
    name: "Tonari no Totoro",
    year: "1988",
    director: "Hayao Miyazaki",
    img: "./assets/img/8.jpg",
    lore: "Gia đình Kusakabe chuyển về vùng thôn quê sinh sống. Căn nhà mới mà họ sắp ở dân làng đồn đại là bị ma ám. Nhưng điều ấy chẳng làm lay chuyển nỗi tò mò, hiếu động của hai chị em nhà Kusakabe: Satsuki và Mei. Tại ngôi nhà mới, Satsuki và Mei kết thân với bà hàng xóm tốt bụng tên Nanny và cậu bé Kanta, cùng tuổi với Satsuki. Trong một lần chạy chơi vào khu rừng gần nhà, cô em gái Mei mới 4 tuổi đã tình cờ gặp gỡ con thú khổng lồ, vị chúa tể của khu rừng. Mei không những không sợ hãi mà còn trèo lên cái bụng bự của nó mà nghịch ngợm. Cô bé đặt tên cho con vật kì lạ này là Totoro, theo tên con thú trong cuốn sách tranh của cô. Sau đó do mệt nên Mei dần ngủ thiếp đi, tới khi tỉnh lại, Totoro đã biến mất. Khi Mei kể về con vật kì lạ ấy, cô chị Satsuki cũng muốn được gặp Totoro một lần.",
    info: "Hàng xóm của tôi là Totoro (となりのトトロ / Tonari no Totoro trong tiếng Nhật, My Neighbor Totoro trong tiếng Anh) là một phim hoạt hình Nhật Bản được hãng Ghibli sản xuất vào năm 1988, vua hoạt hình của Nhật Bản Miyazaki Hayao viết kịch bản và đạo diễn. 'Hàng xóm của tôi là Totoro' có thể coi là một trong những phim hoạt hình lớn đầu tiên của Hayao Miyazaki, tác phẩm này vui tươi, trong sáng, phù hợp với mọi lứa tuổi và thành phần. Nó mở màn cho loạt hoạt hình vẽ bằng tay sau này.",
  },
  {
    id: 9,
    name: "Omoide no Marnie",
    year: "2014",
    director: "Yonebayashi Hiromasa",
    img: "./assets/img/9.jpg",
    lore: "Satsuki Anna là một cô bé sống khép kín, không có bạn bè và sau khi bà ngoại chết thì cô bé được chuyển đến trại trẻ mồ côi và sau đó đến sống cùng với cha mẹ nuôi. Trong một lần phát hiện bức thư chứa nội dung liên quan đến tiền trợ cấp hàng tháng từ chính quyền địa phương. Anna bắt đầu nghi ngờ tình thương của cha mẹ nuôi. Sau một cơn hen suyễn nặng. Anna được gửi về nhà họ hàng của mẹ nuôi ở Kushiro, một thị trấn bên bờ biển để nghỉ ngơi, dưỡng bệnh. Tại đây, Anna bị thu hút bởi một ngôi nhà cũ kĩ bên kia đầm lầy và không ngừng tìm đến nó để khám phá. Nhờ đó, cô bé đã gặp được một cô gái bí ẩn bằng tuổi Anna tên là Marnie.",
    info: "Omoide no Marnie (思い出のマーニー nghĩa đen: Marnie trong ký ức?) là một phim anime của Studio Ghibli công chiếu năm 2014, được dựa trên tiểu thuyết When Marnie Was There (Khi Marnie ở đó) bởi Joan G. Robinson. Kịch bản và đạo diễn phim là Yonebayashi Hiromasa, người từng rất thành công với bộ phim Karigurashi no Arrietty.[1][2]",
  },
  {
    id: 10,
    name: "Gedo Senki",
    year: "29/7/2006",
    director: "Miyazaki Gorō",
    img: "./assets/img/10.jpg",
    lore: "Khi phi hành đoàn của một chiến hạm đang vật lộn với một cơn bão thì bất ngờ xuất hiện hai con rồng chiến đấu kịch liệt với nhau trên bầu trời. Rồng Đen giết chết Rồng Trắng một cách đột ngột, một sự kiện được cho là chưa từng xảy ra trong nhiều thế kỷ.Tin tức về vương quốc suy tàn cùng sự vắng bóng tin tức từ Hoàng tử Arren khiến Vua nước Enlad thịnh vượng một thời trở nên bất an. Thuật sĩ Root đề cập đến mối liên hệ giữa loài người và rồng từng được coi là 'một' cho đến khi bị chia cắt bởi những ham muốn riêng (lần lượt là tự do và tài sản), điều này dẫn đến sự mất cân bằng dần dần của thế giới. Bất ngờ, nhà vua bị ám sát bởi chính con trai mình, Hoàng tử Arren, kẻ đã đánh cắp thanh kiếm của phụ vương và bỏ trốn khỏi lâu đài.",
    info: "Huyền thoại đất liền và đại dương (Nhật: ゲド戦記, ゲドせんき Hepburn: Gedo Senki), là một bộ anime chủ đề kỳ ảo do Ghibli thực hiện và Miyazaki Gorō đạo diễn, được công chiếu vào năm 2006. Bộ phim kết hợp các yếu tố cùng các nhân vật trong bốn cuốn sách đầu của bộ tiểu thuyết Earthsea do Ursula K. Le Guin thực hiện là: A Wizard of Earthsea, The Tombs of Atuan, The Farthest Shore và Tehanu. Nhưng bộ phim có cốt truyện hoàn toàn khác. Nội dung câu chuyện xoay quanh Arren, người đã ám sát vua của Enlad, lấy đi thanh kiếm phép thuật, rồi được pháp sư Sparrowhawk cứu khi đang ở sa mạc. Cả hai người lên đường đến Hort Town và chiến đấu với một pháp sư khác, người muốn đoạn lấy cuộc sống vĩnh hằng bằng các phép thuật bị cấm.",
  },
  {
    id: 11,
    name: "Hauru no Ugoku Shiro",
    year: "5/9/2004",
    director: "Miyazaki Hayao",
    img: "./assets/img/11.jpg",
    lore: "Sophie là một cô thợ làm mũ trẻ và là chị cả trong gia đình có ba chị em gái. Cô tình cờ gặp chàng pháp sư Howl trên đường đến thăm em gái Lettie. Khi trở về nhà, cô bị Phù thủy Vùng hoang địa yểm bùa biến thành một cụ già chín mươi tuổi. Sophie đành lên đường tìm kiếm cách phá bỏ lời nguyền. Trên đường đi, cô gặp một con bù nhìn biết đi và đặt tên cho nó là 'Đầu củ cải'. Nó dẫn cô đến lâu đài di động của Howl. Sau khi tự tiện tiến vào lâu đài, Sophie gặp Markl, học trò nhỏ tuổi của Howl, và Calcifer, con quỷ lửa nắm giữ phép thuật và khả năng di chuyển của lâu đài. Calcifer thỏa thuận với Sophie rằng sẽ hoá giải lời nguyền của cô nếu cô có thể phá bỏ mối liên kết giữa cậu và Howl. Khi Howl trở về, Sophie nói với anh rằng cô đã tự thuê mình làm người giúp việc của lâu đài.",
    info: "Lâu đài bay của pháp sư Howl (ハウルの動く城 Hauru no Ugoku Shiro?, tựa tiếng Anh là Howl's Moving Castle), hay Lâu đài di động của Howl, là một bộ phim điện ảnh hoạt hình Nhật Bản thuộc thể loại kỳ ảo năm 2004 do Miyazaki Hayao đạo diễn kiêm viết kịch bản, dựa trên tiểu thuyết cùng tên năm 1986 của nữ tác giả người Anh Diana Wynne Jones. Bộ phim do Suzuki Toshio sản xuất, với phần đồ hoạ hoạt hình của Studio Ghibli và do Toho phân phối. Hai diễn viên lồng tiếng chính cho phiên bản tiếng Nhật bao gồm Baisho Chieko và Kimura Takuya, còn các diễn viên lồng tiếng Anh là Jean Simmons, Emily Mortimer và Christian Bale. Lấy bối cảnh một vương quốc hư cấu nơi mà cả phép thuật và công nghệ tiên tiến đầu thế kỷ 20 cùng tồn tại, câu chuyện xoay quanh Sophie, cô thợ làm mũ trẻ luôn bằng lòng với cuộc sống bình lặng của mình. Sau khi bị một mụ phù thủy yểm bùa biến thành bà già, Sophie gặp được pháp sư Howl và cùng anh chống lại nhà vua, người yêu cầu anh tham gia vào cuộc chiến tranh với nước láng giềng.",
  },
  {
    id: 12,
    name: "Tenkuu no Shiro Laputa",
    year: "2/8/1986",
    director: "Hayao Miyazaki",
    img: "./assets/img/12.jpg",
    lore: "Theo truyền thuyết, loài người bị bầu trời cuốn hút, bởi vậy họ gia tăng việc tạo ra những phương thức phức tạp để nâng những chiếc máy bay khỏi mặt đất. Điều đó thậm chí đã tạo ra những thành phố và những pháo đài bay. Thời gian trôi qua, những thành phố đó đã rơi trở lại mặt đất, buộc những người sống sót phải sống trên mặt đất như trước kia. Chỉ có thành phố Laputa được cho là vẫn còn lơ lửng trên bầu trời, ẩn giấu giữa những xoáy mây của một cơn bão khổng lồ. Trong khi hầu hết mọi người đều cho đó chỉ là tưởng tượng, một vài người tin rằng truyền thuyết đó là có thật và đã cố gắng tìm kiếm thành phố cổ đó.",
    info: "Tenkuu no Shiro Laputa (Nhật: 天空の城ラピュタ, てんくうのしろラピュタ Việt: Lâu đài trên không Laputa) là một bộ phim năm 1986, biên kịch và đạo diễn bởi Hayao Miyazaki. Đây là bộ phim đầu tiên mà Studio Ghibli sản xuất và phát hành, dù có một vài ý kiến cho rằng đây là bộ phim thứ hai kể từ khi Kaze no Tani no Nausicaä được hai sáng lập viên tạo ra hai năm trước. Tenkuu no Shiro Laputa đã đoạt giải Animage Anime Grand Prix năm 1986. Cái tên Laputa được đặt theo tên của hòn đảo bay Laputa trong tiểu thuyết Những chuyến du hành của Gulliver của tác giả Jonathan Swift.",
  },
  {
    id: 13,
    name: "Neko no Ongaeshi",
    year: "19/7/2002",
    director: "Morita Hiroyuki",
    img: "./assets/img/13.jpg",
    lore: "Cốt truyện xoay quanh Haru một nữ sinh trung học sau khi cô cứu được một chú mèo lạ khỏi bị xe tông, cô đã nhận được sự cảm kích của những chú mèo và sau đó cô được đưa đến vương quốc của loài mèo để trở thành vợ của thái tử. Cuộc phiêu lưu của Haru bắt đầu.",
    info: "Loài mèo trả ơn (Nhật: 猫の恩返し, ねこのおんがえし Hepburn: Neko no Ongaeshi) là một phim anime do hãng Studio Ghibli thực hiện với bàn tay của đạo diễn Morita Hiroyuki. Bộ phim được chuyển thể từ loạt manga cùng tên của Hiiragi Aoi. Phim được công chiếu lần đầu vào ngày 19 tháng 7 năm 2002. Bộ phim đã giành được giải xuất sắc trong Liên hoan Nghệ thuật truyền thông Nhật Bản năm 2002. Tại Việt Nam, phim được chiếu trên kênh SAM - BTV11 vào ngày 8 tháng 5 năm 2016 đến ngày 10 tháng 5 năm 2016.",
  },
  {
    id: 14,
    name: "Mimi o Sumaseba",
    year: "15/7/1995",
    director: "Kondō Yoshifumi",
    img: "./assets/img/14.jpg",
    lore: "Nhân vật nữ chính - Tsukishima Shizuku - một học sinh trung học 14 tuổi sống cùng bố mẹ trong một căn hộ chung cư ở Tama New Town, thuộc Tây Tokyo. Cô rất thích đọc sách và có một người bạn thân tên Harada Yuko. Chuyện bắt đầu khi cô phát hiện các thẻ mượn sách thư viện luôn xuất hiện cái tên Amasawa Seiji. Trong lần đi gặp Yuko tại trường, cô gặp một cậu học sinh - người mà sau này cô mới biết là Seiji. Cô có cái nhìn không thiện cảm với cậu trong lần gặp này. Trên chuyển tàu điện đến thư viện địa phương, cô phát hiện con mèo Moon (Muta). Con mèo dẫn cô đến của hàng đồ cổ. Tại đây, cô bé quen biết ông Nishi Shiro và lần đầu tiên gặp bức tượng con mèo tên Baron Humbert von Gikkingen.",
    info: "Lời thì thầm của trái tim ( 耳をすませば Mimi wo Sumaseba?, nghĩa đen: Nếu lắng nghe kỹ), (tiếng Anh: Whisper of the Heart) là phim thứ 8 (theo thứ tự thời gian công chiếu tại rạp) trong danh sách các phim chính kịch dạng anime của Studio Ghibli.Đạo diễn của phim là Kondō Yoshifumi với kịch bản được Miyazaki Hayao chuyển thể từ manga cùng tên của Aoi Hiiragi. Đây cũng là phim chiếu rạp đầu tiên của Studio Ghibli mà đạo diễn không phải là Miyazaki Hayao hay Takahata Isao.Phim được công chiếu vào ngày 15 tháng 7 năm 1995 cùng một phim ngắn khác của Studio Ghibli là On Your Mark.",
  },
  {
    id: 15,
    name: "Hotaru no Haka",
    year: "16/4/1988",
    director: "Takahata Isao",
    img: "./assets/img/15.jpg",
    lore: "Được đặt trong bối cảnh giai đoạn cuối của Chiến tranh thế giới 2 ở Nhật Bản, bộ phim kể lại câu chuyện chua xót nhưng cảm động về tình anh em của hai đứa trẻ mồ côi người anh trai tên là Seita và em gái của cậu là Setsuko. Hai anh em mất mẹ sau cuộc thả bom dữ dội của không quân Mỹ vào thành phố Kobe trong khi cha của hai đứa đang chiến đấu cho Hải quân Đế quốc Nhật Bản. Trong cả bộ là viễn cảnh Seita và Setsuko phải vật lộn để tồn tại giữa một bên là nạn đói và một bên là sự thờ ơ đến nhẫn tâm của những người xung quanh (trong đó có cả những người họ hàng của hai đứa trẻ và cụ thể chính là người dì ích kỷ của 2 đứa trẻ, người luôn phàn nàn rằng họ không làm việc gì cả nhưng vẫn được chăm sóc chu đáo trong khi thực phẩm ngày càng khan hiếm). Sau khoảng thời gian 2 anh em sống trong sự mắng chửi, phân biệt đối xử và cậu bé Seita phải đối diện với một lựa chọn đó là hoặc ở lại với người dì ích kỷ, làm việc và đối diện với sự thật, hoặc là chạy trốn, để có được sự tự do mặc dù sẽ rất khó khăn, thiếu thốn nhưng 2 anh em cậu sẽ làm được những điều mình thích.",
    info: "Mộ đom đóm (火垂るの墓 Hotaru no Haka?, Grave of the Fireflies) là một bộ phim hoạt hình Nhật Bản của hãng phim hoạt hình Ghibli sản xuất và được Toho phát hành năm 1988. Phim do đạo diễn Takahata Isao viết kịch bản và đạo diễn. Bộ phim được dựa theo cuốn tiểu thuyết cùng tên của Nosaka Akiyuki vốn được tác giả viết dưới dạng bán tự truyện như là một lời xin lỗi với người em gái của chính tác giả. Giống như các tác phẩm khác của hãng Ghibli, bộ phim được chú ý nhờ đạt được chất lượng cao cả về mặt nghệ thuật và hình ảnh.",
  },
  {
    id: 16,
    name: "Kokuriko zaka Kara",
    year: "16/7/2011",
    director: "Miyazaki Gorō",
    img: "./assets/img/16.jpg",
    lore: "Matsuzaki Umi là một nữ sinh 16 tuổi của trường trung học Isogo, sống tại Coquelicot Manor, một căn nhà nội trú, nơi nhìn ra cảng Yokohama Nhật Bản. Ryoko, mẹ cô, là một giáo sư y khoa du học tại Mỹ. Umi điều hành ngôi nhà, chăm sóc 2 em nhỏ Sora và Riku và bà Hana. Cô sinh viên đại học Sachiko Hirokouji và bác sĩ thực tập Hokuto Miki cũng sống ở đây. Mỗi sáng, Umi đều kéo những lá cờ hiệu với thông điệp 'Cầu mong chuyến đi thuận buồm xuôi gió'.",
    info: "Ngọn đồi hoa hồng anh (Nhật: コクリコ坂から; Romanji: Kokuriko zaka Kara; tiếng Anh: From Up on Poppy Hill) là bộ anime do Studio Ghibli thực hiện, dưới sự đạo diễn của Miyazaki Gorō, kịch bản do Miyazaki Hayao (cha của đạo diễn) và Niwa Keiko sáng tác, thiết kế nhân vật bởi Kondō Katsuya. Bộ phim được chuyển thể từ loạt manga cùng tên được vẽ bởi Takahashi Chizuru và được viết bởi Sayama Tetsurō. Bộ phim đã được công chiếu lần đầu ở Nhật Bản vào ngày 16 tháng 7 năm 2011 và trở thành bộ phim Nhật Bản có doanh thu cao nhất trong năm 2011.",
  },
  {
    id: 17,
    name: "Rupan Sansei: Kariosutoro no Shiro",
    year: "15/12/1979",
    director: "Hayao Miyazaki",
    img: "./assets/img/17.jpg",
    lore: "Tên trộm bậc thầy Lupin III và đồng nghiệp của anh ta, Daisuke Jigen, chạy trốn khỏi sòng bạc Monte Carlo với số lượng lớn tiền bị đánh cắp, nhưng khi họ ăn mừng vụ trộm mới nhất của họ, Lupin nhận ra các hóa đơn là hàng giả chất lượng cao đặc biệt. [a] Quyết định tìm kiếm nguồn gốc, họ đi đến Đại công quốc Cagliostro, nguồn gốc được cho là của hàng giả.",
    info: "Lupin III: Lâu đài Cagliostro (tiếng Nhật: ルパン三世 カリオストロの城, Hepburn: Rupan Sansei: Kariosutoro no Shiro) là một bộ phim hoạt hình hài phiêu lưu hành động Nhật Bản năm 1979 do Hayao Miyazaki đồng sáng tác và đạo diễn, với hoạt hình do Tokyo Movie Shinsha sản xuất. Đây là bộ phim hoạt hình thứ hai có tên trộm bậc thầy Lupin III của Monkey Punch, từ bộ truyện tranh cùng tên của ông. Bộ phim là tác phẩm đầu tay của đạo diễn Miyazaki sau khi trước đó đã từng làm việc như một nhà làm phim hoạt hình cho Toei Animation và Telecom Animation Film và đạo diễn một số chương trình truyền hình, bao gồm Lupin the Third Part I.",
  },
  {
    id: 18,
    name: "Umi ga Kikoeru",
    year: "5/5/1993",
    director: "Tomomi Mochizuki",
    img: "./assets/img/18.jpg",
    lore: "Ở Kōchi, Morisaki Taku nhận được một cuộc gọi từ người bạn của mình, Yutaka Matsuno, yêu cầu gặp nhau tại trường trung học của họ. Anh tìm thấy Yutaka với một nữ sinh chuyển trường hấp dẫn, Rikako Muto, người mà Yutaka được yêu cầu dẫn đi xung quanh. Rikako có năng khiếu học tập và giỏi thể thao, nhưng cũng kiêu ngạo. Taku tin rằng cô không hài lòng về việc rời Tokyo.",
    info: "Ocean Waves, được biết đến ở Nhật Bản với tên I Can Hear the Sea (tiếng Nhật: 海がきこえる, Hepburn: Umi ga Kikoeru), là một bộ phim truyền hình lãng mạn dành cho lứa tuổi mới lớn của Nhật Bản năm 1993 do Mochizuki Tomomi đạo diễn và Niwa Keiko viết kịch bản (được ghi là Nakamura Kaori) dựa trên cuốn tiểu thuyết cùng tên năm 1990–1992 của Himuro Saeko. Hoạt hình bởi Studio Ghibli cho Tokuma Shoten và Nippon Television Network, Ocean Waves được phát sóng lần đầu tiên vào ngày 5 tháng 5 năm 1993, trên Nippon TV. Bộ phim lấy bối cảnh ở thành phố Kōchi, và theo chân một mối tình tay ba phát triển giữa hai người bạn tốt và một cô gái mới chuyển đến trường trung học của họ từ Tokyo.",
  },
  {
    id: 19,
    name: "Karigurashi no Arrietty",
    year: "17/7/2010",
    director: "Yonebayashi Hiromasa",
    img: "./assets/img/19.jpg",
    lore: "Một cậu bé tên là Shō kể rằng cậu vẫn còn nhớ tuần lễ mùa hè cậu đến ở nhà thời thơ ấu của mẹ với người dì tuyệt vời của mẹ mình, Sadako, và người giúp việc nhà, Haru. Khi Shō đến nhà vào ngày đầu tiên, anh thấy một con mèo, Niya, đang cố tấn công thứ gì đó trong bụi rậm, nhưng nó bỏ cuộc sau khi bị con quạ tấn công. Shō thoáng thấy Arrietty, một cô gái vay mượn trẻ tuổi, trở về nhà qua một lỗ thông hơi dưới lòng đất.",
    info: "Thế giới bí mật của Arrietty (Nhật: 借りぐらしのアリエッティ Hepburn: Karigurashi no Arrietty?) là một phim anime kỳ ảo công chiếu năm 2010 do Yonebayashi Hiromasa đạo diễn với cốt truyện viết bởi Miyazaki Hayao và Niwa Keiko và hãng Studio Ghibli thực hiện dựa trên cuốn tiểu thuyết The Borrowers của Mary Norton. Bộ phim xoay quanh cô gái Arrietty một người tí hon sống bên dưới nền nhà, là bạn thân của Sho một cậu bé có vấn đề về tim mạch từ khi được sinh ra đang sống tại nhà của cô mình.",
  },
  {
    id: 20,
    name: "Sen to Chihiro no Kamikakushi",
    year: "20/7/2001",
    director: "Miyazaki Hayao",
    img: "./assets/img/20.jpg",
    lore: "Chihiro Ogino là một cô bé 10 tuổi, đang cùng gia đình chuyển đến nhà mới thì cha cô rẽ nhầm một con đường lạ. Họ vô tình bước vào một thế giới ma thuật mà cha của Chihiro kiên quyết khám phá. Khi cha mẹ của Chihiro ăn tại một nhà hàng không người, cô tìm thấy một nhà tắm công cộng tráng lệ. Cô gặp một chàng trai trẻ, Haku, người khuyên cô mau trở lại con sông trước khi trời tối. Dù vậy, Chihiro phát hiện ra đã quá trễ, cha mẹ cô đã bị biến thành heo và cô không thể vượt qua con sông khi thủy triều đang dâng cao, khiến cô bị mắc kẹt trong thế giới linh hồn.",
    info: "Sen và Chihiro ở thế giới thần bí (Nhật: 千せんと千尋ちひろの神隠かみかくし Hepburn: Sen to Chihiro no Kamikakushi?, tựa tiếng Anh: Spirited Away; tựa Việt khác là Vùng đất linh hồn) là một bộ phim điện ảnh hoạt hình Nhật Bản đề tài tuổi mới lớn và kỳ ảo công chiếu năm 2001 do Miyazaki Hayao làm đạo diễn kiêm nhà biên kịch. Tác phẩm do xưởng phim Studio Ghibli sản xuất cho Tokuma Shoten, Nippon Television Network, Dentsu, Buena Vista Home Entertainment, Tohokushinsha Film và Mitsubishi; bên cạnh đó công ty Toho là đơn vị chịu trách nhiệm phát hành phim.[6] Phim có sự diễn xuất lồng tiếng của Hiiragi Rumi, Irino Miyu, Natsuki Mari, Naito Takeshi, Sawaguchi Yasuko, Kamijō Tsunehiko, Ono Takehiko và Sugawara Bunta. Cốt truyện phim kể về câu chuyện của Ogino Chihiro (Hiiragi), một cô bé 10 tuổi luôn buồn chán; trong khi chuyển đến ngôi nhà mới thì cô bị lạc vào thế giới linh hồn của tín ngưỡng dân gian Thần đạo Nhật Bản.[7] Sau khi cha mẹ mình bị phù thủy Yubaba (Natsuki) biến thành heo, Chihiro buộc phải làm việc tại nhà tắm công cộng của Yubaba để tìm cách giải thoát cha mẹ và mình và trở về với thế giới loài người.",
  },
];
