export const dataArticles = [
  {
    id: 1,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "./assets/img/2.jpg",
  },
  {
    id: 2,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "./assets/img/a2.jpg",
  },
  {
    id: 3,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 4,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
  {
    id: 5,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 6,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
  {
    id: 7,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 8,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
  {
    id: 9,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 10,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
  {
    id: 11,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 12,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
  {
    id: 13,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 14,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
  {
    id: 15,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 16,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
  {
    id: 17,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 18,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
  {
    id: 19,
    title: "Article Title 1",
    summary: "This is a short summary of the first article.",
    content: "Full content of the first article goes here...",
    image: "https://example.com/image1.jpg",
  },
  {
    id: 20,
    title: "Article Title 2",
    summary: "This is a short summary of the second article.",
    content: "Full content of the second article goes here...",
    image: "https://example.com/image2.jpg",
  },
];
